version: '3.8'

services:
  backend:
    build: .
    container_name: face_recognition_backend
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./static
        target: /app/static
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: face_recognition_frontend
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./static
        target: /usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped 